### ISSUE TITLE
Gib Porybox

### ISSUE THREAD

**Issue by YaManicKill** [porygonco/porybox#1]
Because issue number 1 is always a good one to have sitting around being weird and not actionable, I created this.

2 years ago, we heard that pokecheck was getting gen 6 support at the #endofthemonth. 6 months later, it shut down for good.

We are a team of people trying to change this. We are making a replacement. 

Acceptance criteria:
We have a version of porybox that allows people to upload pokemon, share information with people, and they can do a reasonable amount of LA (yes, intentionally vague, here).

**Comment by YaManicKill** [comment]
Acceptance criteria amendment suggestion:

We have a version of porybox that allows people to upload pokemon, share information with people, and they can do **clone check**.

Are we happy with this becoming the non-vague definition of when this ticket is resolved?

**Comment by NotRaia** [comment]
👍

**Comment by not-an-aardvark** [comment]
\o/

**Comment by TheSonAlsoRises** [comment]
Porybox has been gibben!
