### ISSUE TITLE
Retrieving a lost username

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#10]
Acceptance criteria:
Given that the email is known in the db
Ensure that the associated nick is emailed to the address

**Comment by not-an-aardvark** [comment]
For this and #9, we will need to create a something@porybox.com email address.

It might be simplest to just set it up as a gmail account, and then use [the gmail api](https://developers.google.com/gmail/api/quickstart/nodejs) to send things.

**Comment by YaManicKill** [comment]
FWIW, we wouldn't need to. We can send emails without having a real registered email address.

The only reason we would need a real mailbox is if we want to support replies. Which we probably won't.

**Comment by TheSonAlsoRises** [comment]
The support should be limited to IRC, GitHub and maybe the dedicated subreddit. If we can avoid setting up an email address, let's do so.
