### ISSUE TITLE
Default boxes

### ISSUE THREAD

**Issue by not-an-aardvark** [porygonco/porybox#128]
Continuing discussion from #126

We currently have the backend set up so that a user is not required to specify a box while uploading something. If the user doesn't specify anything, the upload goes into a new box, called "Untitled" followed by a timestamp. This isn't exactly the most intuitive behavior.

A few other options:

* Require a user to explicitly specify a box when uploading
* Have an undeleteable "Transport Box" that all new uploads go into if the box isn't otherwise specified
* Have a "default" box for each user, which can be switched around at will. This seems like the best option so far, but there are a few decisions to make:
  * What if a user wants to delete the box that has "default" status? Should the "default" status automatically move to another box? If so, which one?
  * What happens if the user's default box is their last one, and they want to delete it?

**Comment by Kirzi** [comment]
Last option, except don't let them delete the default box? They can transfer the "default" status to another box and then delete the box though.

**Comment by NotRaia** [comment]
The last option, but the user should always have at least one box. They shouldn't be able to delete their last box.

**Comment by TheSonAlsoRises** [comment]
Agreed with Raia, have a non-removable default box.

**Comment by not-an-aardvark** [comment]
> If the user deletes the default box and other boxes exist, then automatically switch their default to the next box.

How is the "next box" defined?

**Comment by NotRaia** [comment]
The first displayed non-default box in the user interface.

Let's say there are three boxes displayed in order A, B (default), and C. If the user deletes B, then A should become the default.

**Comment by NotRaia** [comment]
Update: I think we decided to drop the default box idea and just have the last box uploaded to be the one displayed first in the dropdown.

**Comment by YaManicKill** [comment]
Alright, I'll re-open though, because we still need to remove the existing functionality to create a new unnamed box.

@not-an-aardvark So what we need is the call to fail if we don't send a box id.
