### ISSUE TITLE
Editing the account’s information.

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#13]
Editable account information (not displayed on profile):
- Password (mandatory)
- Email address (mandatory)

Profile information (displayed publicly on profile):
- FCs/IGNs/TSVs (optional)
- Third-party side authentication (reddit, twitter?)

Preferences:
- Unlisted/listed for new boxes
- Default privacy setting for new uploads

**Comment by YaManicKill** [comment]
I shall implement the frontend to this if not already done on the 25th/26th of June.

**Comment by YaManicKill** [comment]
Oops, closed the wrong one.

**Comment by YaManicKill** [comment]
Picking this up again.

**Comment by YaManicKill** [comment]
I'll split out the email and the third-party sites bits.

**Comment by not-an-aardvark** [comment]
Pretty much everything on this list is done except for editing one's email account, and we now have a separate issue for that: #377
