### ISSUE TITLE
Add multiple uploads for pokemon

### ISSUE THREAD

**Issue by YaManicKill** [porygonco/porybox#132]
We currently only allow 1 pokemon to be uplaoded at one time. We should allow multiple. 

Maybe included with this should drag and drop? So you can drag a folder or a number of pk6/pkx files and it'll throw them in a list, you choose the box/privacy. Boom, sorted.

**Comment by NotRaia** [comment]
>Maybe included with this should drag and drop? So you can drag a folder or a number of pk6/pkx files and it'll throw them in a list, you choose the box/privacy. Boom, sorted.

Yup, definitely.
