### ISSUE TITLE
Uploading a pk6 to a box

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#14]
Acceptance criteria:
Given that the user is identified
And that the submitted pk6 is valid
Ensure that the Pokémon is parsed and stored in the db
And that it is associated to a box.

**Comment by NotRaia** [comment]
How the upload window might look: http://i.imgur.com/AkKuQ7Q.jpg
Comes up as part of the main box view (which is incomplete in this, ignore it)

**Comment by TheSonAlsoRises** [comment]
When uploading a Pokémon:

* Choose a box where the Pokémon will be uploaded to;
 * Give the option to create a new box?
* Select the Pokémon's privacy settings
 * Default to Private
