### ISSUE TITLE
Creating boxes

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#15]
Acceptance criteria:
Given that the user is identified
Ensure that new boxes can be created and assigned a name/description.

**Comment by YaManicKill** [comment]
Its not finished yet, because we can't choose the name and description yet.

**Comment by not-an-aardvark** [comment]
Whoops, I forgot that it would get closed automatically with the PR.

**Comment by not-an-aardvark** [comment]
As a progress update, the serverside portion for this has been ready for awhile, but the clientside portion is still not done.
