### ISSUE TITLE
Make large sprites easier to access

### ISSUE THREAD

**Issue by NotRaia** [porygonco/porybox#162]
We have large sprites for the full Pokémon view from the Pokédex, with basically everything accounted for (gender differences, forms/megas, shininess). However, the files are all named like this: http://i.imgur.com/Z4uWsYL.png

In order to complete the full view, we need an easy way to get the correct sprite given a Pokémon's gender, form, and shininess.

**Comment by not-an-aardvark** [comment]
If the only issue is that the files are named annoyingly, could we just run a script to rename them all?

**Comment by NotRaia** [comment]
Yeah, that would probably be the best option.
