### ISSUE TITLE
Box won't load if pk6parse can't parse one of the pk6's

### ISSUE THREAD

**Issue by NotRaia** [porygonco/porybox#166]
If even one pk6 file causes errors with pk6parse, the entire box will not load. Ideally, the page should still load so that the user can delete the bad pk6.

**Comment by not-an-aardvark** [comment]
Now that d5c8abfeb368c6edd2301764e408bddcc834339b has been merged, the server should disallow uploads that cause errors with pk6parse, so I don't think this should be a problem anymore.
