### ISSUE TITLE
When uploading a pokemon (when inside a box) pokemon isn't displayed

### ISSUE THREAD

**Issue by YaManicKill** [porygonco/porybox#169]
There's no feedback that it was successful, other than the modal goes away. We should add the pokemon to the list.

**Comment by NotRaia** [comment]
Yeah, I'd like for there to be some feedback that the upload was successful no matter where you are on the site.

**Comment by NotRaia** [comment]
https://material.angularjs.org/1.0.1/demo/toast

This looks like it could be pretty cool for a "success" alert.

**Comment by YaManicKill** [comment]
Alrighty, yeah, I'll use that for success across the rest of the site, but in another ticket.
