### ISSUE TITLE
Validate pk6 uploads

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#173]
Unsure if it is not already the case, but we should try to make sure the uploaded pk6 is valid on upload and block it if it is not.

**Comment by YaManicKill** [comment]
Define valid? Just every bit being a valid bit for where it is? Do we want to block these, or do we want to allow them and put a hack warning on them?

**Comment by TheSonAlsoRises** [comment]
>Define valid? Just every bit being a valid bit for where it is?

Make sure the checksum (0x06-0x07) is valid, maybe?	

>Do we want to block these, or do we want to allow them and put a hack warning on them?

Depends on how well the UI can handle it. We don't have any hack checks in place as of today.

**Comment by YaManicKill** [comment]
> We don't have any hack checks in place as of today.

True, but that would be at least an easy one to add once we have decided what it means (we are planning on the clone check before launch, aren't we? So it wouldn't be the only one).

> Depends on how well the UI can handle it.

I was thinking just a "valid pk6" thing on the pokemon view, without any information other than "Yes" or something like "Bad pk6 structure" or something.

> Make sure the checksum (0x06-0x07) is valid, maybe?

I think I need to read up on how the pk6 works properly :-P 

What is the checksum and how does it get calculated?

**Comment by TheSonAlsoRises** [comment]
>we are planning on the clone check before launch, aren't we?

The clone checker should already be done at this point.

>I was thinking just a "valid pk6" thing on the pokemon view, without any information other than "Yes" or something like "Bad pk6 structure" or something.

That could work.

>What is the checksum and how does it get calculated?

I have no idea how it works, or even if the algorithm is known.

**Comment by not-an-aardvark** [comment]
We already run the checksum test and some basic sanity tests, and return a 400 error if any of those are invalid.

However, we don't do more advanced sanity checks such as making sure all the move IDs actually correspond to real moves.

**Comment by TheSonAlsoRises** [comment]
Alright. We will have to test how Porybox reacts when presented with invalid move/abilities/pkm IDs.
