### ISSUE TITLE
Dragging and dropping Pokémon around in a box.

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#20]

**Comment by NotRaia** [comment]
Might have headings that user can add. [Shitty sketch of concept](http://i.imgur.com/HLSOm39.jpg)

**Comment by not-an-aardvark** [comment]
In terms of the backend, will the Pokémon in a box be "swapped", or will they be "inserted"?

i.e.

swapping:
```js
box.contents //  [a, b, c, d, e]
swap(b, e)
box.contents // [a, e, c, d, b]
```

inserting:

```js
box.contents // [a, b, c, d, e]
insert(e, 1)
box.contents // [a, e, b, c, d]
```

Also, will it be possible to swap/insert between two different boxes?

**Comment by TheSonAlsoRises** [comment]
>In terms of creating the backend, will the UI cause Pokémon in a box be "swapped", or "inserted"?

Inserting makes more sense to me in terms of behavior.

>Also, will it be possible to swap/insert between two different boxes?

I do not see a strong need to have this.

**Comment by not-an-aardvark** [comment]
When a Pokémon is moved to a different box, should it just appear at the end of the list in that box, then?

**Comment by TheSonAlsoRises** [comment]
That would be a logical behavior indeed.

**Comment by not-an-aardvark** [comment]
:+1:

**Comment by not-an-aardvark** [comment]
Implementation notes:

It seems like waterline's one-to-many collections aren't inherently ordered, so we're probably going to have to implement ordering within boxes ourselves.

If we're optimizing for inserting as opposed to swapping, then the best way to do that is probably to store the boxes as linked-lists, with each item storing the id of its neighbor. That way we won't have to update all of the records in a box when we want to move two things around.

**Comment by YaManicKill** [comment]
Sounds good. My only issue is I'm not sure how well the linked list would
work client side. But if we can use it to generate an ordered array server
side that we send back to the client, that would work. Only question is how
do we send information back to the server to say we have reordered it. We
don't want to have to send the whole array back to the server. I guess we
could send the id of the one moving and the id of the one that is now
pointing to it?

**Comment by not-an-aardvark** [comment]
That would work. We could even combine it with the existing endpoint that moves stuff to an existing box -- so the endpoint would accept `oldPokemonId`, `newIndex` and `newBox` (probably optional, defaulting to the current box),  and shift stuff around as necessary.

I agree that the server should arrange the linked-list into an ordered array -- the client doesn't have to be concerned with anything related to the linked-list.

**Comment by YaManicKill** [comment]
In that case, sounds good. Makes my job easier while having some nice
efficiencies. I'll hopefully get some stuff done this week. Wife is away
Thursday and Friday nights.
