### ISSUE TITLE
Edit pokemon settings

### ISSUE THREAD

**Issue by YaManicKill** [porygonco/porybox#205]
Visibility I think is the only thing for pokemon?

**Comment by TheSonAlsoRises** [comment]
There should also be:
* delete the Pokémon
* add/edit/remove notes (might not be in the backend yet?)
* move the Pokémon from one box to another

**Comment by not-an-aardvark** [comment]
> add/edit/remove notes (might not be in the backend yet?)

It is already in the backend.

**Comment by YaManicKill** [comment]
I'll close this as we have #290 for moving pokemon, and we'll create another for notes
