### ISSUE TITLE
Editing a Pokémon's settings

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#22]
- Adding and editing notes
- Changing the note's privacy settings
- Changing the Pokémon's privacy settings

For reference, Pokémon have the following visibility settings:
* Publicly downloadable: all the information obtained from the pk6 is visible and the pk6 is retrievable by logged-out users.
* Private: no one but the owner and the site admins have access to the Pokémon’s information.
* Viewable: the information is visible for logged-in and logged-out users. For static PID events, only the information that could not be used for duplication is available publicly (PID, EC, IVs). The pk6 cannot be downloaded but by the owner.

Notes can be:
- private: visible only to the owner
- public: visible to logged-out users

Acceptance criteria:
Given that the user is identified
And that the Pokémon exists
And that the Pokémon is associated to the user’s account
Ensure that the settings of the Pokémon is updated.

**Comment by TheSonAlsoRises** [comment]
See #62 for boxes settings.

**Comment by TheSonAlsoRises** [comment]
Can Pokémon notes (and box descriptions) support markdown formatting?

**Comment by not-an-aardvark** [comment]
At the moment they're just stored as plain text, so it should be possible for the client to render them in markdown.

**Comment by TheSonAlsoRises** [comment]
Alright, if it is not too much trouble to implement we can have it for the 1.0 beta; otherwise it will wait.
