### ISSUE TITLE
Pokemon at L100 show as "0/37876 exp to next level"

### ISSUE THREAD

**Issue by YaManicKill** [porygonco/porybox#226]
They probably shouldn't say that, because it's the highest level.

Probably best just to say "No next level" or something similar.

![a0529c8bc5203bcf4d3979903385e83d](https://cloud.githubusercontent.com/assets/2162657/16446876/cb67170e-3de1-11e6-9e0f-323c25fa54ea.png)

**Comment by NotRaia** [comment]
This is more of a pk6parse issue than a Porybox one.

**Comment by not-an-aardvark** [comment]
Well, we'll probably want to change the porybox display regardless assuming we don't want it to say `0 / Infinity exp to next level`.

**Comment by NotRaia** [comment]
That's true. Alright, I'll fix it tonight.
