### ISSUE TITLE
It is difficult to interact with a box that has a lot of things in it

### ISSUE THREAD

**Issue by not-an-aardvark** [porygonco/porybox#247]
The UI becomes extremely slow. This might be because angular has to perform calculations for each thing in the box.

This test was done by uploading a folder containing 720 Pokémon into a box.

A fix might be to only do part of the parsing procedure when viewing a Pokémon in a box (or to only send some of the data from the server).

**Comment by YaManicKill** [comment]
Or page the boxes.

**Comment by not-an-aardvark** [comment]
That works, but I imagine that if people are going to have to use multiple clicks to get through their boxes anyway, we might as well just have put things in multiple boxes.

The filtering addition in #248 does help a bit, but I think the best long-term goal would be to either (a) paginate internally and load more content on scrolling, or (b) put a limit on how large boxes can be.

**Comment by YaManicKill** [comment]
I didn't mean necessarily manual paging, but it could do automatic loading
as you scroll, as you mention.
