### ISSUE TITLE
TM/HM icon no longer displays correctly in box view

### ISSUE THREAD

**Issue by NotRaia** [porygonco/porybox#261]
Likely a result of b529eb27287b789bc10533baec95c3f3af3674e3. TMs/HMs are all supposed to display `tm.png` when held, but now the box view is requesting the full item name (in this case, `hm01.png`) and we get a 404.

http://i.imgur.com/c9lQQNY.png

**Comment by not-an-aardvark** [comment]
Adding `heldItemId` to the `POKEMON_FIELDS` list in `client/box/box.ctrl.js` should fix this.

Although I'm wondering how you got your wurmple to hold a TM anyway.

**Comment by NotRaia** [comment]
That works, thanks.

>Although I'm wondering how you got your wurmple to hold a TM anyway.

It's not mine, it wasn't me!
