### ISSUE TITLE
Drop area gets hidden

### ISSUE THREAD

**Issue by DoubleFried** [porygonco/porybox#306]
When you drop stuff into the Pokemon Upload square 1 by 1 the Pokemon that appear push down the area off screen and you have to scroll down in the menu.

**Comment by YaManicKill** [comment]
Thanks, doobs. I think it would probably be best to stick the dropzone and the upload input at the top, and have the pokemon come underneath it. That would be better.

**Comment by not-an-aardvark** [comment]
I think this was fixed in #375.
