### ISSUE TITLE
Add nice frontend to 502 for when porybox is down

### ISSUE THREAD

**Issue by YaManicKill** [porygonco/porybox#308]

**Comment by not-an-aardvark** [comment]
![](https://www.pokecheck.org/i/flygon.png)

**Comment by YaManicKill** [comment]
Damnit, you literally just made me spit out my milk.

**Comment by not-an-aardvark** [comment]
This is fixed, we now have a [maintenance page](https://www.porybox.com/porybox-maintenance.html).
