### ISSUE TITLE
PKHeX incompatibility issue

### ISSUE THREAD

**Issue by DoubleFried** [porygonco/porybox#309]
When dragging .pk6 files directly from PKHeX into Porybox it returns "an unexpected error".

**Comment by not-an-aardvark** [comment]
Does it say anything in the dev console when that happens?

**Comment by DoubleFried** [comment]
21:49:03 <DoubleFried> tried to upload a bunch of mons
21:49:06 <DoubleFried> unexpected error
21:49:20 <YaManicKill> Don't do anything.
21:49:22 <YaManicKill> Open console.
21:49:23 <YaManicKill> What's there?
21:49:51 <DoubleFried> Unhandled rejection (<{"isTrusted":true}>, no stack trace) bundle.min.js:18:30986
21:49:51 <DoubleFried> error { target: FileReader, isTrusted: true, lengthComputable: true, loaded: 0, total: 232, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1468093695058000, originalTarget: FileReader }
21:50:45 <YaManicKill> Did any pokemon upload?
21:50:48 <DoubleFried> second line expands to show  
	[6]</</<() 
	tryCatcher() bundle.min.js:20

	[43]</</</<[22]</t.exports/T.prototype._settlePromiseFromHandler() bundle.min.js:19

	[43]</</</<[22]</t.exports/T.prototype._settlePromise() bundle.min.js:19

	[43]</</</<[22]</t.exports/T.prototype._settlePromise0() bundle.min.js:19

	[43]</</</<[22]</t.exports/T.prototype._settlePromises() bundle.min.js:19

	[43]</</</<[2]</s.prototype._drainQueue() bundle.min.js:18

	[43]</</</<[2]</s.prototype._drainQueues() bundle.min.js:18

	s/this.drainQueues() bundle.min.js:18

	[245]</O/</a() bundle.min.js:23

	[245]</O/<() bundle.min.js:23

	[110]</t.exports/u() bundle.min.js:21
21:50:57 <DoubleFried> none
21:51:19 <YaManicKill> Are any of the pokemon obvious terrible hacks>?
21:51:37 <DoubleFried> how dare u
21:51:38 <DoubleFried> no
21:52:00 <DoubleFried> i dragged them directly from PKHeX
21:52:03 <YaManicKill> Can you make sure your cache is fully cleared, refresh and try it again.
21:52:09 <YaManicKill> lol
21:52:23 <DoubleFried> HeX not HaX
21:52:26 <DoubleFried> im a gud boy
21:52:57 <YaManicKill> Try saving them locally and uploading them from the local files rather than straight from pkhex
21:53:13 <DoubleFried> ive refreshed my cache etc
21:53:23 <DoubleFried> do you want the local treatment first or trying again from pkhex
21:53:38 <YaManicKill> local please
21:54:36 <YaManicKill> Delayed 15 more minutes. Last time, hopefully.
21:54:44 <DoubleFried> works now
21:54:50 <DoubleFried> though i didnt do all of them
21:54:54 <YaManicKill> Try straight from pkhex
21:55:19 <DoubleFried> error
21:55:32 <YaManicKill> Try just doing 1 single 1 from pkhex
21:55:40 <YaManicKill> One that uploaded fine from a local fil
21:56:15 <DoubleFried> still error
21:58:01 <YaManicKill> Great, that's fine, it's something specific to pkhex
21:58:05 <YaManicKill> That'll be easier to debug
21:58:05 <YaManicKill> Thanks

**Comment by kwsch** [comment]
With the following commit to PKHeX I was able to upload files directly from the program.

https://github.com/kwsch/PKHeX/commit/109bd291f696823db21749c9f930d0159186f6aa

**Before:**
File created in temp folder -> file moved to _location_, file deleted. 
**After:**
File created in temp folder -> file moved to _location_, **wait [delay]**, file deleted. 

Waiting 100ms before deleting the file was enough time for Chrome to get the data.
I figured 500ms would be safer :smile:

**Comment by YaManicKill** [comment]
Cool, closing. Thanks @kwsch
