### ISSUE TITLE
Add BST, total EVs and HP info to the Stats card

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#335]

**Comment by not-an-aardvark** [comment]
`hiddenPowerType` and `hiddenPowerPower` have been added to pk6parse as of v0.10.14.

**Comment by NotRaia** [comment]
Thanks, I'll make a PR later tonight or tomorrow.

**Comment by NotRaia** [comment]
Should BST and total EVs be in pk6parse too? We could calculate it here, but it might make sense to just add them to pk6parse.

**Comment by not-an-aardvark** [comment]
¯\\\_(ツ)_/¯

I guess they could, but I would lean against adding them. There's a difference between something like getting an item name from an ID (which is clearly part of extracting data from a pk6 file, and requires the library to possess specific pokemon-related knowledge), versus computing a BST (which is just adding six numbers together). There are a lot of ways that one could theoretically represent a Pokémon's data, but pk6parse will get bloated if we try to include them all.

**Comment by NotRaia** [comment]
Alright, I'll just add them together here then.
