### ISSUE TITLE
Notes over 2000 characters get lost to error

### ISSUE THREAD

**Issue by NotRaia** [porygonco/porybox#357]
If a user tries to enter a note that is over 2000 characters long, it gets rejected with the "An unexpected error occurred" toast.

Two possible solutions:

* Save a truncated version of the note
* Show a character count in the edit window that turns red once they pass 2000.

I'm leaning towards the second one, along with an error displaying in the modal if they try to save (rather than a toast) so that they don't lose their progress.

**Comment by not-an-aardvark** [comment]
The second one sounds better; we could also disable the 'save' button if the note is above 2000 characters.

**Comment by NotRaia** [comment]
Yeah, disabling it is good.
