### ISSUE TITLE
Pressing back after viewing pokemon should go to previous page number, not first.

### ISSUE THREAD

**Issue by HighMans** [porygonco/porybox#368]
After viewing a pokemon, pressing the back button should bring the user to the previous page number they were on, not the first page.

For example, if I'm on the 5th page, view a pokemon, and then press the back button, it should bring me to page 5 not page 1.

**Comment by not-an-aardvark** [comment]
Thanks for the report. Now that box pages don't exist anymore, this issue isn't really applicable, so I'm going to close it for now.
