### ISSUE TITLE
Unlisted boxes should not show on your own profile when logged in

### ISSUE THREAD

**Issue by NotRaia** [porygonco/porybox#397]
Boxes that are unlisted should probably never be shown on the user's profile, so that the user can easily verify which boxes are listed publicly.

Right now, all of the boxes I have display on my own profile when logged in.

**Comment by not-an-aardvark** [comment]
Is this a bug? I thought this was supposed to happen -- otherwise, a user would have no way to find their unlisted boxes.

A better way to distinguish them might be to add an icon indicating that they're unlisted, similar to how github has an icon next to secret gists.

**Comment by NotRaia** [comment]
The unlisted boxes should display on the homepage, but not on the profile.

We could do an icon if we figure out what looks good and isn't already taken by Pokémon privacy settings.
