### ISSUE TITLE
Infinite scroll not working when zoomed out

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#415]
When browsing a box, the infinite scroll will not trigger if your browser zoom is lower than 100%. It works as expected on 100% and greater.

**Comment by TheSonAlsoRises** [comment]
[Or maybe not](https://www.reddit.com/r/pokemontrades/comments/4uzi0f/daily_discussion_question_thread_for_28_july_2016/d5u9ox2?context=3)...

**Comment by TheSonAlsoRises** [comment]
[Other instance](https://www.reddit.com/r/porybox/comments/4uziir/july_28th_2016_update/d5udjmy).

**Comment by not-an-aardvark** [comment]
> And I just made the width smaller, once the scrolling bar appeared it allowed me to view more pokemon, so it seems it's a bug where it doesn't work if you can't scroll down.

That's probably it; we're testing whether the box should load as the user scrolls, but if they have a large monitor they might not be able to scroll.
