### ISSUE TITLE
[Feature Request] Possibility of deleting boxes with pokémon inside.

### ISSUE THREAD

**Issue by Sotin** [porygonco/porybox#427]
Currently it's impossible to delete boxes with pokémon inside (at least my boxes). I'm really sorry for reposting it, but I did not know if you'd read the second message since you've closed the issue.

**Comment by not-an-aardvark** [comment]
It is already possible to delete boxes with Pokémon inside.

You might be experiencing this issue because you only have one box, and it is impossible to delete your last box. As a workaround, I suppose you could create another empty box and then delete the box with Pokémon in it.

**Comment by Sotin** [comment]
Yeah, thank you for helping and sorry for disturbing you TWICE :P
