### ISSUE TITLE
Option to bold OT/ID

### ISSUE THREAD

**Issue by Kirzi** [porygonco/porybox#459]
Would be useful to let users check an option that bolds or otherwise emphasizes the OT/ID of all Pokemon in the boxes they're viewing. Mainly for event collectors who mostly rely on those to distinguish between events and are browsing/skimming through big boxes.

**Comment by not-an-aardvark** [comment]
This seems like sort of a small thing to have an option for; would it work if the OT was just bolded by default?

**Comment by NotRaia** [comment]
It might look weird, as the Species is already bolded.

Trying it out:

![](http://i.imgur.com/cb242wn.png)

**Comment by Kirzi** [comment]
Maybe bold+italics or bold+some other color instead?

**Comment by not-an-aardvark** [comment]
I think I'm -1 on this issue, it seems like an arbitrary thing to make bold and there's not much reason to do so.

**Comment by Raia** [comment]
@not-an-aardvark, I agree, I'm not really a fan of how it looks.

**Comment by not-an-aardvark** [comment]
Alright, going to close for the time being. We can come back to it later if we come up with a good solution.
