### ISSUE TITLE
IV of 0 results in a "-"

### ISSUE THREAD

**Issue by Kirzi** [porygonco/porybox#463]
Example: https://i.gyazo.com/9ab6eed01844f25c4282fc320ba26b40.png

It has a defense IV of 0, but instead of displaying "0" in the IV column of the stats box, it displays "-".

**Comment by not-an-aardvark** [comment]
Caused by [this](/porygonco/porybox/blob/master/client/pokemon/pokemon-full.view.html#L176); we're checking for whether the value is truthy rather than checking whether it exists.
