### ISSUE TITLE
Rage Candy Bar

### ISSUE THREAD

**Issue by Droidem** [porygonco/porybox#466]
I uploaded my Volcanion from the JPN movie event and the Rage Candy Bar picture is broken. looked at the source and it shows 

`<img` draggable="false" class="held-item ng-scope" ng-if="::pokemon.heldItemUrl" ng-src="/img/icons/items/rage-candy bar.png" title="Holding Rage Candy Bar" src="/img/icons/items/rage-candy bar.png">"`

The space between candy and bar needs to be replaced by a "-" according to how it's uploaded to your website.  https://www.porybox.com/img/icons/items/rage-candy-bar.png

**Comment by not-an-aardvark** [comment]
Thanks for the bug report; this will be fixed the next time we deploy to production.
