### ISSUE TITLE
Make contents of unlisted boxes unlisted

### ISSUE THREAD

**Issue by Raia** [porygonco/porybox#478]
Last thing for 1.0.

Unlisted means:

* Not being linked in clone lists (but still having an entry listed, like what we have with Private stuff)
* Not showing up in search results or on a user's profile

When viewing an unlisted box through the link, the visibility of the contents depends on the Pokémon's setting as usual.

* Private = invisible to other users
* Viewable = viewable but not downloadable
* Public = viewable and downloadable

**Comment by YaManicKill** [comment]
> Not showing up in search results

Not a thing yet, though.

**Comment by not-an-aardvark** [comment]
Finished in #493
