### ISSUE TITLE
Legality Analysis discussion

### ISSUE THREAD

**Issue by YaManicKill** [porygonco/porybox#499]
So, I guess we need to discuss the legality analysis stuff.

To get it, we have multiple options:  

1. Write it all ourselves

This will take a long time, but means all the code is our own. Will we have time for it? There's a lot to think about and a lot that other people have already figured out.

2. Use pkhex's code (probably using copper's library that he's building)

This is by far the best legality code out there, but it is GPL. We are currently apache, so we will need to either convince Kaph and the other contributors to change, or we will have to change. The former probably won't happen, so the latter is the most likely situation

3. Use showdown's code

I think this is MIT, so it would be a lot easier to include into the app, but it isn't anywhere near as good, and mainly just has moves.

So.

I'm very against us moving to GPL as I am massively against the idea of forcing people to share changes to code. In my opinion it goes against the whole idea of FLOSS and I have no clue how people actually ever are happy with forcing our opinions on other people. I much prefer licenses (like Apache, MIT, BSD etc) that allow people to just use the code without resharing it if they want. 

However, I understand that we really need LA for porybox to be fully useful, and realistically we should use kaph's code because he has put so much effort into it, and it means that any changes we make to it can be included back to him. 

So, for that one I reluctantly have to conclude that option 2 with us changing our code to a 2-way GPL compatible license is the only way we can go.

Please, someone, prove me wrong.

**Comment by YaManicKill** [comment]
Actually, just thought of a 4th option.

Create a new project that only does our legality, which porybox communicates with somehow (via REST or something) meaning that could be GPL, and the rest of it could be apache, as it won't be bundling the software in any way, just communicating with another server.

Might be ott, but it's another option.

**Comment by not-an-aardvark** [comment]
I would much rather either use showdown's code or write it all ourselves. That said, I think if it's a high priority to get something working quickly, option 4 would also be viable.

**Comment by TheSonAlsoRises** [comment]
The LA should be our top priority if we want the site to be used by more people. We already have our side project, but development has stalled. I would rather reuse PKHeX's LA rather than reinventing the wheel.

**Comment by Raia** [comment]
I would also prefer to use PKHeX's LA rather than reinventing the wheel.

**Comment by YaManicKill** [comment]
So, this conversation kinda... stopped.

**Comment by not-an-aardvark** [comment]
I think we reached a consensus on option 4, but we can't really use that until we there's a checker that works somewhere other than Windows.

**Comment by YaManicKill** [comment]
In that case, I'm going to start just building our own LA, because there are at least some things we can do really easily (balls for example).

No point in doing no LA until we have something to use.

**Comment by not-an-aardvark** [comment]
I assume you're aware of this (it's hard to tell from your wording), but we [already started our own LA](https://github.com/porygonco/pokemon-legality-checker).

**Comment by YaManicKill** [comment]
Alright, closing this because I thin kwe are agreed that we will work on our own LA until something else is available. It looks like copper is dead, so I wouldn't expect his to be done anytime soon.
