### ISSUE TITLE
Themed error pages

### ISSUE THREAD

**Issue by not-an-aardvark** [porygonco/porybox#51]
(low-priority)

Eventually we'll probably want themed error pages. We should have one for:

* 403 Access denied
* 404 Not found
* 500 Internal server error

**Comment by blackaurora** [comment]
![403 Access Denied](https://cloud.githubusercontent.com/assets/11909976/14359094/f3135eda-fcbd-11e5-97bf-20ca2e228315.png)
![404 Not Found](https://cloud.githubusercontent.com/assets/11909976/14359095/f313c2da-fcbd-11e5-87af-9642ba4f8ede.png)
![500 Internal Server Error](https://cloud.githubusercontent.com/assets/11909976/14359096/f313ca14-fcbd-11e5-8371-45a4a7379fa3.png)
