### ISSUE TITLE
Merging/fast-forward

### ISSUE THREAD

**Issue by YaManicKill** [porygonco/porybox#518]
Alright.

Let's have a discussion on the merging/fast-forwarding in github.

I can see the advantage of the fast-forwarding, so I guess I would be happy with moving to that.

Thoughts?

**Comment by not-an-aardvark** [comment]
I think my first choice would be squash merging, but I would prefer fast-forwarding over what we have now.

**Comment by Raia** [comment]
Squash or fast-forwarding both sound fine to me.

**Comment by YaManicKill** [comment]
Ok, I have enabled squash merge and rebase merge, and disabled merge-commit merge.

My reasoning behind having the 2 enabled is that occaisionally we might want to have multiple commits if there is a reason for it.

So, the default should be squash-merge, unless we have multiple commits that are logically different.

Re-open if not happy.
