### ISSUE TITLE
Displaying the Pokémon's information

### ISSUE THREAD

**Issue by not-an-aardvark** [porygonco/porybox#58]
(I split #32 into two separate issues, this is the clientside portion)

Given a Pokémon's data from the server, which will sometimes be missing certain information (PID, IVs, etc.)
Ensure that the info is displayed on the screen in an aesthetically pleasing format.

**Comment by NotRaia** [comment]
Layout: http://imgur.com/a/b9DHu

**Comment by TheSonAlsoRises** [comment]
Updated layout:

* Summary: http://i.imgur.com/XDdUoke.png
* Misc info: http://i.imgur.com/w883mXK.png
* LA: http://i.imgur.com/Ug8S1FY.png & http://i.imgur.com/1u8LmE3.png

**Comment by YaManicKill** [comment]
Is there anything actually left to do one this, @NotRaia ?

**Comment by TheSonAlsoRises** [comment]
It is missing memories and region names, but naa is supposed to take care of that on pk6parse.

**Comment by YaManicKill** [comment]
Alrighty, @NotRaia are the FE hooks for those already there and we just waiting on @not-an-aardvark ? Or is there still some FE work?

**Comment by NotRaia** [comment]
Mostly waiting on pk6parse and Pokémon settings so we can add notes. There are also a few display enhancements we could do (like make ribbons and ST prettier) but besides those it's about done.

**Comment by YaManicKill** [comment]
Ok, it sounds to me like this is ready to be closed, and we can open individual things for the other things. The pkparse stuff is in #174 and we can have a seperate story for showing the notes. Does that sound right, or would you prefer them being in this story? It just feels like we don't have a proper end to this story.
