### ISSUE TITLE
Legality analysis: clone checking

### ISSUE THREAD

**Issue by TheSonAlsoRises** [porygonco/porybox#65]
For info, a clone is when the OT/TID/SID/PID/EC/species line match. For static PID events, the IVs must also match.

Display the following information: see http://i.imgur.com/XZbJJYL.jpg

**Comment by not-an-aardvark** [comment]
The clone-checking part of this has been done for a little while. It doesn't identify powersaves details yet, but that's sort of a separate issue and it's worth discussing whether that's even necessary, so I'm going to close this one for now.

**Comment by TheSonAlsoRises** [comment]
>It doesn't identify powersaves details yet, but that's sort of a separate issue and it's worth discussing whether that's even necessary

Given the circulation of PowerSaves devices and hacks, I will really push for a dates database once we get a basic LA off the ground.
