### ISSUE TITLE
Privacy Policy + ToS

### ISSUE THREAD

**Issue by not-an-aardvark** [porygonco/porybox#73]
We should probably have a privacy policy page somewhere that details how we handle uploaded data, email addresses, etc.

**Comment by TheSonAlsoRises** [comment]
If we have a privacy policy, then we will probably need terms of service as well. Use at your own risk, no guarantees, etc.

**Comment by TheSonAlsoRises** [comment]
* Privacy policy: http://pastebin.com/xEAd4njF
* ToS: http://pastebin.com/2Tq8PA8N

**Comment by TheSonAlsoRises** [comment]
An updated version of the documents is available here:
* PP: https://docs.google.com/document/d/1PX4zSEk6s6K04ZYiR0M3TO3zm51Iyw96tDk4XeGTxIE/edit?usp=sharing
* ToS: https://docs.google.com/document/d/1hP2npwBXtrTHx0Hp2Fj64jQwJ74Zk1IsVRg61_0kjIc/edit?usp=sharing

**Comment by YaManicKill** [comment]
This shouldn't be too hard. If we stick a thing in the footer for them, and they can pop up in a modal.

**Comment by NotRaia** [comment]
I don't think a modal is strictly necessary, let's just have a dedicated page and prioritize other things.
