### ISSUE TITLE
Having long box names or descriptions can cause the boxes themselves to expand

### ISSUE THREAD

**Issue by not-an-aardvark** [porygonco/porybox#95]
See [here](https://i.gyazo.com/491eebaa748a324094e423dd999c6f9a.png)

We should probably truncate the names/descriptions that get shown.

**Comment by YaManicKill** [comment]
This should probably be fixed by #94 when it gets merged.

**Comment by not-an-aardvark** [comment]
The horizontal spacing issue seems to be fixed, but it still displays strangely if the box name/description have a lot of words. ([example](https://i.gyazo.com/b724bb07422688eb34eb83b3cebf259e.png))

**Comment by YaManicKill** [comment]
Oh damn, I forgot about multiple words in the title. You'll notice that the same thing happening in the description doesn't happen. I'll fix that.

**Comment by not-an-aardvark** [comment]
This was fixed in #94.
